version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    container_name: marsmission-backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    container_name: marsmission-frontend
    depends_on:
      - backend


networks:
  default:
    name: marsmission-network
